
package cn.majingjing.ws.server.file;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FilePortImplService", targetNamespace = "http://file.server.ws.majingjing.cn/", wsdlLocation = "http://127.0.0.1:8080/ws/file?wsdl")
public class FilePortImplService
    extends Service
{

    private final static URL FILEPORTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FILEPORTIMPLSERVICE_EXCEPTION;
    private final static QName FILEPORTIMPLSERVICE_QNAME = new QName("http://file.server.ws.majingjing.cn/", "FilePortImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8080/ws/file?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FILEPORTIMPLSERVICE_WSDL_LOCATION = url;
        FILEPORTIMPLSERVICE_EXCEPTION = e;
    }

    public FilePortImplService() {
        super(__getWsdlLocation(), FILEPORTIMPLSERVICE_QNAME);
    }

    public FilePortImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FILEPORTIMPLSERVICE_QNAME, features);
    }

    public FilePortImplService(URL wsdlLocation) {
        super(wsdlLocation, FILEPORTIMPLSERVICE_QNAME);
    }

    public FilePortImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FILEPORTIMPLSERVICE_QNAME, features);
    }

    public FilePortImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FilePortImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FilePortImpl
     */
    @WebEndpoint(name = "FilePortImplPort")
    public FilePortImpl getFilePortImplPort() {
        return super.getPort(new QName("http://file.server.ws.majingjing.cn/", "FilePortImplPort"), FilePortImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FilePortImpl
     */
    @WebEndpoint(name = "FilePortImplPort")
    public FilePortImpl getFilePortImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://file.server.ws.majingjing.cn/", "FilePortImplPort"), FilePortImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FILEPORTIMPLSERVICE_EXCEPTION!= null) {
            throw FILEPORTIMPLSERVICE_EXCEPTION;
        }
        return FILEPORTIMPLSERVICE_WSDL_LOCATION;
    }

}
